export const tagIcons = {
	typescript: 'logos/typescript',
	javascript: 'logos/javascript',
	git: 'logos/git',
	rust: 'logos/rust',
	astro: 'logos/astro',
	svelte: 'logos/svelte',
	'github-actions': 'logos/github-actions',
	react: 'logos/react',
	vim: 'logos/neovim',
	'mental-health': 'brain',
	cli: 'terminal',
	tools: 'wrench',
	photography: 'camera',
	camera: 'camera',
	database: 'database',
	'computer-science': 'computer',
	'advent-of-code': 'logos/advent-of-code',
	testing: 'list-checks',
	science: 'microscope',
	typography: 'type',
	medicine: 'briefcase-medical',
	deployment: 'rocket',
	'web-dev': 'web-dev',
	golang: 'logos/go',
	fallback: 'hash',
} as const;
