import {
	Adventofcode,
	Astro,
	Git,
	Githubactions,
	Go,
	Javascript,
	Neovim,
	Opensourceinitiative,
	React,
	Rust,
	Svelte,
	Typescript,
} from 'simple-icons-astro';

import {
	Brain,
	BriefcaseMedical,
	Camera,
	Computer,
	Hash,
	ListChecks,
	Microscope,
	PanelsTopLeft,
	RocketIcon,
	TerminalIcon,
	Type,
	Wrench,
} from '@lucide/astro';

export const tagIcons = {
	typescript: Typescript,
	javascript: Javascript,
	'open-source': Opensourceinitiative,
	git: Git,
	rust: Rust,
	astro: Astro,
	svelte: Svelte,
	'github-actions': Githubactions,
	react: React,
	vim: Neovim,
	'mental-health': Brain,
	cli: TerminalIcon,
	tools: Wrench,
	photography: Camera,
	'computer-science': Computer,
	'advent-of-code': Adventofcode,
	testing: ListChecks,
	science: Microscope,
	typography: Type,
	medicine: BriefcaseMedical,
	deployment: RocketIcon,
	'web-dev': PanelsTopLeft,
	golang: Go,
	fallback: Hash,
} as const;
